/**
 * Wikipedia API + Open Library integration for Starmeet
 * 1000+ real global celebrities — actors, musicians, footballers & more
 */

const WIKI_API = 'https://en.wikipedia.org/w/api.php';
const OL_API   = 'https://openlibrary.org';

// ─── Wikipedia category top-up (runs after seed list) ─────────────────────
export const WIKI_CATEGORIES = [
  { cat: '21st-century_American_male_actors',       label: 'Actor',          cap: 300 },
  { cat: '21st-century_American_actresses',         label: 'Actress',        cap: 300 },
  { cat: 'British_male_film_actors',                label: 'Actor',          cap: 150 },
  { cat: 'British_actresses',                       label: 'Actress',        cap: 150 },
  { cat: 'Indian_male_film_actors',                 label: 'Actor',          cap: 100 },
  { cat: 'Indian_actresses',                        label: 'Actress',        cap: 100 },
  { cat: '21st-century_American_singers',           label: 'Musician',       cap: 200 },
  { cat: 'American_hip_hop_musicians',              label: 'Musician',       cap: 150 },
  { cat: 'American_pop_singers',                    label: 'Musician',       cap: 150 },
  { cat: 'British_pop_singers',                     label: 'Musician',       cap: 100 },
  { cat: 'American_film_directors',                 label: 'Director',       cap: 100 },
  { cat: 'American_film_producers',                 label: 'Movie Producer', cap:  80 },
  { cat: 'American_stand-up_comedians',             label: 'Comedian',       cap: 120 },
  { cat: 'American_female_models',                  label: 'Model',          cap: 100 },
  { cat: 'National_Basketball_Association_players', label: 'Athlete',        cap: 150 },
  { cat: 'National_Football_League_players',        label: 'Athlete',        cap: 150 },
  { cat: 'American_YouTubers',                      label: 'Creator',        cap: 100 },
];

// ─── 1000+ curated global celebrities ─────────────────────────────────────
// [WikipediaPageTitle, StarmeetCategory]
export const SEED_CELEBRITIES = [

  // ══════════════════════════════════════════════════════
  // HOLLYWOOD ACTORS — specifically requested + more
  // ══════════════════════════════════════════════════════
  ['Johnny Depp','Actor'],
  ['Jason Momoa','Actor'],
  ['Paul Wesley','Actor'],
  ['Tom Hanks','Actor'],
  ['Leonardo DiCaprio','Actor'],
  ['Brad Pitt','Actor'],
  ['Denzel Washington','Actor'],
  ['Will Smith','Actor'],
  ['George Clooney','Actor'],
  ['Robert De Niro','Actor'],
  ['Morgan Freeman','Actor'],
  ['Tom Cruise','Actor'],
  ['Dwayne Johnson','Actor'],
  ['Ryan Reynolds','Actor'],
  ['Matt Damon','Actor'],
  ['Chris Evans','Actor'],
  ['Joaquin Phoenix','Actor'],
  ['Christian Bale','Actor'],
  ['Robert Downey Jr.','Actor'],
  ['Michael Fassbender','Actor'],
  ['Benedict Cumberbatch','Actor'],
  ['Hugh Jackman','Actor'],
  ['Jake Gyllenhaal','Actor'],
  ['Ryan Gosling','Actor'],
  ['Idris Elba','Actor'],
  ['Anthony Hopkins','Actor'],
  ['Gary Oldman','Actor'],
  ['Al Pacino','Actor'],
  ['Samuel L. Jackson','Actor'],
  ['Timothée Chalamet','Actor'],
  ['Pedro Pascal','Actor'],
  ['Paul Mescal','Actor'],
  ['Austin Butler','Actor'],
  ['Andrew Garfield','Actor'],
  ['Jeremy Renner','Actor'],
  ['Daniel Radcliffe','Actor'],
  ['Daniel Craig','Actor'],
  ['Keanu Reeves','Actor'],
  ['Tom Hardy','Actor'],
  ['Chris Hemsworth','Actor'],
  ['Chris Pratt','Actor'],
  ['Mark Ruffalo','Actor'],
  ['Paul Rudd','Actor'],
  ['Jeremy Irons','Actor'],
  ['Ralph Fiennes','Actor'],
  ['Jude Law','Actor'],
  ['Colin Firth','Actor'],
  ['Hugh Grant','Actor'],
  ['Ewan McGregor','Actor'],
  ['Liam Neeson','Actor'],
  ['Pierce Brosnan','Actor'],
  ['Harrison Ford','Actor'],
  ['Mel Gibson','Actor'],
  ['Bruce Willis','Actor'],
  ['Arnold Schwarzenegger','Actor'],
  ['Sylvester Stallone','Actor'],
  ['Michael B. Jordan','Actor'],
  ['Rami Malek','Actor'],
  ['Oscar Isaac','Actor'],
  ['Mahershala Ali','Actor'],
  ['Daniel Kaluuya','Actor'],
  ['John Boyega','Actor'],
  ['Chiwetel Ejiofor','Actor'],
  ['David Oyelowo','Actor'],
  ['Richard Madden','Actor'],
  ['Kit Harington','Actor'],
  ['Peter Dinklage','Actor'],
  ['Nikolaj Coster-Waldau','Actor'],
  ['Joe Dempsie','Actor'],
  ['David Harbour','Actor'],
  ['Eddie Redmayne','Actor'],
  ['Ben Whishaw','Actor'],
  ['Cillian Murphy','Actor'],
  ['Barry Keoghan','Actor'],
  ['Paul Dano','Actor'],
  ['Ezra Miller','Actor'],
  ['Shia LaBeouf','Actor'],
  ['Zac Efron','Actor'],
  ['Channing Tatum','Actor'],
  ['Jamie Foxx','Actor'],
  ['Don Cheadle','Actor'],
  ['Terrence Howard','Actor'],
  ['Laurence Fishburne','Actor'],
  ['Vin Diesel','Actor'],
  ['Paul Walker','Actor'],
  ['Jason Statham','Actor'],
  ['Liam Hemsworth','Actor'],
  ['Dave Bautista','Actor'],
  ['Kumail Nanjiani','Actor'],
  ['Simu Liu','Actor'],
  ['Jonathan Majors','Actor'],
  ['Aldis Hodge','Actor'],
  ['Winston Duke','Actor'],
  ['LaKeith Stanfield','Actor'],
  ['Brian Tyree Henry','Actor'],
  ['Sterling K. Brown','Actor'],
  ['John David Washington','Actor'],
  ['Anthony Mackie','Actor'],
  ['Sebastian Stan','Actor'],
  ['Tom Holland','Actor'],
  ['Jacob Batalon','Actor'],
  ['Finn Wolfhard','Actor'],
  ['Millie Bobby Brown','Actress'],
  ['Noah Schnapp','Actor'],
  ['Joe Keery','Actor'],
  ['Charles Melton','Actor'],
  ['Dylan O\'Brien','Actor'],
  ['Tyler Posey','Actor'],
  ['Tyler Hoechlin','Actor'],
  ['Ian Somerhalder','Actor'],
  ['Steven R. McQueen','Actor'],
  ['Nathaniel Buzolic','Actor'],
  ['Michael Trevino','Actor'],
  ['Zach Roerig','Actor'],
  ['Matt Davis','Actor'],
  ['Cary Elwes','Actor'],
  ['Clive Owen','Actor'],
  ['Sam Claflin','Actor'],
  ['Douglas Booth','Actor'],
  ['Max Irons','Actor'],
  ['Freddie Highmore','Actor'],
  ['Joe Alwyn','Actor'],
  ['Jamie Dornan','Actor'],
  ['Rob Lowe','Actor'],
  ['Josh Brolin','Actor'],
  ['Adrien Brody','Actor'],
  ['Javier Bardem','Actor'],
  ['Antonio Banderas','Actor'],
  ['Gerard Butler','Actor'],
  ['James McAvoy','Actor'],
  ['Michael Sheen','Actor'],
  ['Rupert Grint','Actor'],
  ['Tom Felton','Actor'],
  ['Alan Rickman','Actor'],
  ['Gary Oldman','Actor'],
  ['Idris Elba','Actor'],
  ['David Tennant','Actor'],
  ['Matt Smith','Actor'],
  ['Peter Capaldi','Actor'],
  ['Ncuti Gatwa','Actor'],
  ['Patrick Stewart','Actor'],
  ['Ian McKellen','Actor'],
  ['Christopher Plummer','Actor'],
  ['Jeff Goldblum','Actor'],
  ['Bill Murray','Actor'],
  ['John Cusack','Actor'],
  ['Nicolas Cage','Actor'],
  ['John Travolta','Actor'],
  ['Kevin Costner','Actor'],
  ['Denzel Washington','Actor'],
  ['Morgan Freeman','Actor'],
  ['James Earl Jones','Actor'],
  ['Whoopi Goldberg','Actress'],
  ['Eddie Murphy','Actor'],
  ['Chris Tucker','Actor'],
  ['Ice Cube','Actor'],
  ['Ice-T','Actor'],
  ['Mark Wahlberg','Actor'],
  ['Ben Affleck','Actor'],
  ['Matt Damon','Actor'],
  ['Casey Affleck','Actor'],
  ['Chris Pine','Actor'],
  ['Zachary Quinto','Actor'],
  ['Karl Urban','Actor'],
  ['Zoe Saldana','Actress'],
  ['Vin Diesel','Actor'],
  ['Bradley Cooper','Actor'],
  ['Jared Leto','Actor'],
  ['Tobey Maguire','Actor'],
  ['James Franco','Actor'],
  ['Seth Rogen','Actor'],
  ['Jonah Hill','Actor'],
  ['Jason Segel','Actor'],
  ['Paul Giamatti','Actor'],
  ['Philip Seymour Hoffman','Actor'],
  ['Steve Carell','Actor'],
  ['Ben Stiller','Actor'],
  ['Adam Sandler','Actor'],
  ['Jack Black','Actor'],
  ['Will Ferrell','Actor'],
  ['Vince Vaughn','Actor'],
  ['Owen Wilson','Actor'],
  ['Luke Wilson','Actor'],
  ['John C. Reilly','Actor'],
  ['Steve Martin','Actor'],
  ['Jim Carrey','Actor'],
  ['Robin Williams','Actor'],
  ['Bill Cosby','Actor'],
  ['Richard Pryor','Actor'],
  ['Eddie Griffin','Actor'],
  ['Martin Lawrence','Actor'],
  ['Mike Epps','Actor'],
  ['Cedric the Entertainer','Actor'],
  ['Bernie Mac','Actor'],
  ['D.L. Hughley','Comedian'],
  ['Bob Odenkirk','Actor'],
  ['Bryan Cranston','Actor'],
  ['Aaron Paul','Actor'],
  ['Dean Norris','Actor'],
  ['Giancarlo Esposito','Actor'],
  ['Jonathan Banks','Actor'],
  ['Bob Odenkirk','Actor'],
  ['Vince Gilligan','Director'],

  // ══════════════════════════════════════════════════════
  // HOLLYWOOD ACTRESSES
  // ══════════════════════════════════════════════════════
  ['Meryl Streep','Actress'],
  ['Cate Blanchett','Actress'],
  ['Angelina Jolie','Actress'],
  ['Julia Roberts','Actress'],
  ['Nicole Kidman','Actress'],
  ['Sandra Bullock','Actress'],
  ['Charlize Theron','Actress'],
  ['Jennifer Lawrence','Actress'],
  ['Scarlett Johansson','Actress'],
  ['Emma Stone','Actress'],
  ['Anne Hathaway','Actress'],
  ['Viola Davis','Actress'],
  ['Margot Robbie','Actress'],
  ['Halle Berry','Actress'],
  ['Zendaya','Actress'],
  ['Kate Winslet','Actress'],
  ['Amy Adams','Actress'],
  ['Lupita Nyong\'o','Actress'],
  ['Emily Blunt','Actress'],
  ['Brie Larson','Actress'],
  ['Florence Pugh','Actress'],
  ['Saoirse Ronan','Actress'],
  ['Rachel McAdams','Actress'],
  ['Reese Witherspoon','Actress'],
  ['Gwyneth Paltrow','Actress'],
  ['Natalie Portman','Actress'],
  ['Emma Watson','Actress'],
  ['Keira Knightley','Actress'],
  ['Rachel Weisz','Actress'],
  ['Salma Hayek','Actress'],
  ['Penélope Cruz','Actress'],
  ['Sofia Vergara','Actress'],
  ['Eva Longoria','Actress'],
  ['Jessica Alba','Actress'],
  ['Mila Kunis','Actress'],
  ['Megan Fox','Actress'],
  ['Jessica Biel','Actress'],
  ['Cameron Diaz','Actress'],
  ['Drew Barrymore','Actress'],
  ['Jennifer Aniston','Actress'],
  ['Courteney Cox','Actress'],
  ['Lisa Kudrow','Actress'],
  ['Winona Ryder','Actress'],
  ['Naomi Watts','Actress'],
  ['Cate Blanchett','Actress'],
  ['Tilda Swinton','Actress'],
  ['Julianne Moore','Actress'],
  ['Michelle Pfeiffer','Actress'],
  ['Judi Dench','Actress'],
  ['Helen Mirren','Actress'],
  ['Maggie Smith','Actress'],
  ['Kate Blanchett','Actress'],
  ['Kristin Scott Thomas','Actress'],
  ['Kristin Davis','Actress'],
  ['Sarah Jessica Parker','Actress'],
  ['Kim Cattrall','Actress'],
  ['Cynthia Nixon','Actress'],
  ['Halle Bailey','Actress'],
  ['Gabrielle Union','Actress'],
  ['Taraji P. Henson','Actress'],
  ['Octavia Spencer','Actress'],
  ['Regina King','Actress'],
  ['Kerry Washington','Actress'],
  ['Sandra Oh','Actress'],
  ['Ellen Pompeo','Actress'],
  ['Katherine Heigl','Actress'],
  ['Shonda Rhimes','Movie Producer'],
  ['Priyanka Chopra','Actress'],
  ['Mindy Kaling','Actress'],
  ['Issa Rae','Actress'],
  ['Lena Waithe','Actress'],
  ['Storm Reid','Actress'],
  ['Marsai Martin','Actress'],
  ['Yara Shahidi','Actress'],
  ['Zuri Hall','Actress'],
  ['Sadie Sink','Actress'],
  ['Maya Hawke','Actress'],
  ['Natalia Dyer','Actress'],
  ['Gaten Matarazzo','Actor'],
  ['Caleb McLaughlin','Actor'],
  ['Jamie Campbell Bower','Actor'],
  ['Joe Quinn','Actor'],
  ['Sophie Turner','Actress'],
  ['Maisie Williams','Actress'],
  ['Emilia Clarke','Actress'],
  ['Lena Headey','Actress'],
  ['Natalie Dormer','Actress'],
  ['Gwendoline Christie','Actress'],
  ['Carice van Houten','Actress'],
  ['Michelle Fairley','Actress'],
  ['Nathalie Emmanuel','Actress'],
  ['Rose Leslie','Actress'],
  ['Diane Kruger','Actress'],
  ['Kate Beckinsale','Actress'],
  ['Eva Green','Actress'],
  ['Monica Bellucci','Actress'],
  ['Sophia Loren','Actress'],
  ['Audrey Hepburn','Actress'],
  ['Brigitte Bardot','Actress'],
  ['Catherine Deneuve','Actress'],
  ['Isabelle Huppert','Actress'],
  ['Marion Cotillard','Actress'],
  ['Léa Seydoux','Actress'],
  ['Adèle Exarchopoulos','Actress'],
  ['Virginie Ledoyen','Actress'],
  ['Juliette Binoche','Actress'],
  ['Sophie Marceau','Actress'],
  ['Vanessa Paradis','Actress'],
  ['Audrey Tautou','Actress'],
  ['Ana de Armas','Actress'],
  ['Paz Vega','Actress'],
  ['Penélope Cruz','Actress'],
  ['Elsa Pataky','Actress'],
  ['Freida Pinto','Actress'],
  ['Aishwarya Rai','Actress'],
  ['Deepika Padukone','Actress'],
  ['Alia Bhatt','Actress'],
  ['Katrina Kaif','Actress'],
  ['Kareena Kapoor','Actress'],
  ['Vidya Balan','Actress'],
  ['Kangana Ranaut','Actress'],
  ['Priyanka Chopra','Actress'],
  ['Anushka Sharma','Actress'],
  ['Sonam Kapoor','Actress'],
  ['Shraddha Kapoor','Actress'],
  ['Jacqueline Fernandez','Actress'],
  ['Disha Patani','Actress'],
  ['Kiara Advani','Actress'],
  ['Rashmika Mandanna','Actress'],
  ['Samantha Ruth Prabhu','Actress'],
  ['Nayanthara','Actress'],
  ['Tamannaah Bhatia','Actress'],
  ['Regina Cassandra','Actress'],
  ['Pooja Hegde','Actress'],

  // ══════════════════════════════════════════════════════
  // TURKISH CELEBRITIES (Can Yaman + more)
  // ══════════════════════════════════════════════════════
  ['Can Yaman','Actor'],
  ['Çağatay Ulusoy','Actor'],
  ['Kerem Bürsin','Actor'],
  ['Kıvanç Tatlıtuğ','Actor'],
  ['Burak Özçivit','Actor'],
  ['Engin Akyürek','Actor'],
  ['Barış Arduç','Actor'],
  ['İbrahim Çelikkol','Actor'],
  ['Halit Ergenç','Actor'],
  ['Mehmet Günsür','Actor'],
  ['Baris Falay','Actor'],
  ['Tolga Sarıtaş','Actor'],
  ['Serkan Çayoğlu','Actor'],
  ['Hakan Ural','Actor'],
  ['Alperen Duymaz','Actor'],
  ['Tuba Büyüküstün','Actress'],
  ['Beren Saat','Actress'],
  ['Hazal Kaya','Actress'],
  ['Serenay Sarıkaya','Actress'],
  ['Birce Akalay','Actress'],
  ['Demet Özdemir','Actress'],
  ['Hande Erçel','Actress'],
  ['Neslihan Atagül','Actress'],
  ['Elçin Sangu','Actress'],
  ['Bergüzar Korel','Actress'],
  ['Fahriye Evcen','Actress'],
  ['Özge Gürel','Actress'],
  ['Selin Şekerci','Actress'],
  ['İrem Helvacıoğlu','Actress'],
  ['Şükrü Özyıldız','Actor'],

  // ══════════════════════════════════════════════════════
  // BOLLYWOOD ACTORS
  // ══════════════════════════════════════════════════════
  ['Shah Rukh Khan','Actor'],
  ['Amitabh Bachchan','Actor'],
  ['Salman Khan','Actor'],
  ['Aamir Khan','Actor'],
  ['Akshay Kumar','Actor'],
  ['Hrithik Roshan','Actor'],
  ['Ranbir Kapoor','Actor'],
  ['Ranveer Singh','Actor'],
  ['Tiger Shroff','Actor'],
  ['Varun Dhawan','Actor'],
  ['Siddharth Malhotra','Actor'],
  ['Kartik Aaryan','Actor'],
  ['Ayushmann Khurrana','Actor'],
  ['Vicky Kaushal','Actor'],
  ['Rajkummar Rao','Actor'],
  ['Prabhas','Actor'],
  ['Allu Arjun','Actor'],
  ['Ram Charan','Actor'],
  ['Jr. NTR','Actor'],
  ['Vijay','Actor'],
  ['Rajinikanth','Actor'],
  ['Kamal Haasan','Actor'],
  ['Dulquer Salmaan','Actor'],
  ['Mohanlal','Actor'],
  ['Mammootty','Actor'],
  ['Tovino Thomas','Actor'],
  ['Fahadh Faasil','Actor'],

  // ══════════════════════════════════════════════════════
  // KOREAN / K-DRAMA ACTORS
  // ══════════════════════════════════════════════════════
  ['Lee Min-ho','Actor'],
  ['Park Seo-joon','Actor'],
  ['Kim Soo-hyun','Actor'],
  ['Hyun Bin','Actor'],
  ['Ji Chang-wook','Actor'],
  ['Song Joong-ki','Actor'],
  ['Gong Yoo','Actor'],
  ['Lee Jong-suk','Actor'],
  ['Park Bo-gum','Actor'],
  ['Nam Joo-hyuk','Actor'],
  ['Cha Eun-woo','Actor'],
  ['Yoo Ah-in','Actor'],
  ['Yoo Seung-ho','Actor'],
  ['Joo Won','Actor'],
  ['Lee Joon-gi','Actor'],
  ['Song Hye-kyo','Actress'],
  ['Son Ye-jin','Actress'],
  ['Park Shin-hye','Actress'],
  ['Jun Ji-hyun','Actress'],
  ['Kim Go-eun','Actress'],
  ['Bae Suzy','Actress'],
  ['Han So-hee','Actress'],
  ['Kim Ji-won','Actress'],
  ['Yoona','Actress'],
  ['IU','Musician'],
  ['Seo Ye-ji','Actress'],
  ['Moon Ga-young','Actress'],
  ['Kim Da-mi','Actress'],
  ['Shin Min-a','Actress'],
  ['Jeon Ji-hyun','Actress'],

  // ══════════════════════════════════════════════════════
  // K-POP MUSICIANS
  // ══════════════════════════════════════════════════════
  ['RM (rapper)','Musician'],
  ['Jin (singer)','Musician'],
  ['Suga (rapper)','Musician'],
  ['J-Hope','Musician'],
  ['Jimin (singer)','Musician'],
  ['V (singer)','Musician'],
  ['Jungkook','Musician'],
  ['Jennie (singer)','Musician'],
  ['Lisa','Musician'],
  ['Rosé (singer)','Musician'],
  ['Jisoo','Musician'],
  ['Taeyang','Musician'],
  ['G-Dragon','Musician'],
  ['CL (rapper)','Musician'],
  ['Taeyeon','Musician'],
  ['Baekhyun','Musician'],
  ['Kai (entertainer)','Musician'],
  ['Chanyeol','Musician'],
  ['Suho','Musician'],
  ['Lay Zhang','Musician'],
  ['Chen (singer)','Musician'],
  ['Xiumin','Musician'],
  ['D.O. (entertainer)','Musician'],
  ['Sehun','Musician'],
  ['Heechul','Musician'],
  ['Yesung','Musician'],
  ['Kyuhyun','Musician'],
  ['Joohoney','Musician'],
  ['Felix (rapper)','Musician'],
  ['Hyunjin','Musician'],

  // ══════════════════════════════════════════════════════
  // GLOBAL MUSICIANS — Pop, Hip-Hop, R&B, Latin
  // ══════════════════════════════════════════════════════
  ['Taylor Swift','Musician'],
  ['Beyoncé','Musician'],
  ['Rihanna','Musician'],
  ['Eminem','Musician'],
  ['Lady Gaga','Musician'],
  ['Adele','Musician'],
  ['Ed Sheeran','Musician'],
  ['Justin Bieber','Musician'],
  ['Katy Perry','Musician'],
  ['Bruno Mars','Musician'],
  ['Ariana Grande','Musician'],
  ['The Weeknd','Musician'],
  ['Drake','Musician'],
  ['Billie Eilish','Musician'],
  ['Harry Styles','Musician'],
  ['Post Malone','Musician'],
  ['Dua Lipa','Musician'],
  ['Olivia Rodrigo','Musician'],
  ['Elvis Presley','Musician'],
  ['Michael Jackson','Musician'],
  ['Madonna','Musician'],
  ['Bruce Springsteen','Musician'],
  ['Elton John','Musician'],
  ['Bob Dylan','Musician'],
  ['Stevie Wonder','Musician'],
  ['Whitney Houston','Musician'],
  ['Mariah Carey','Musician'],
  ['Aretha Franklin','Musician'],
  ['Freddie Mercury','Musician'],
  ['David Bowie','Musician'],
  ['Prince','Musician'],
  ['Kendrick Lamar','Musician'],
  ['Nicki Minaj','Musician'],
  ['Cardi B','Musician'],
  ['SZA','Musician'],
  ['Lizzo','Musician'],
  ['Sam Smith','Musician'],
  ['Justin Timberlake','Musician'],
  ['Usher','Musician'],
  ['Alicia Keys','Musician'],
  ['John Legend','Musician'],
  ['Pharrell Williams','Musician'],
  ['Jay-Z','Musician'],
  ['Kanye West','Musician'],
  ['Lil Wayne','Musician'],
  ['Chris Brown','Musician'],
  ['Shakira','Musician'],
  ['Jennifer Lopez','Musician'],
  ['Selena Gomez','Musician'],
  ['Camila Cabello','Musician'],
  ['Halsey','Musician'],
  ['Lana Del Rey','Musician'],
  ['Sia','Musician'],
  ['Miley Cyrus','Musician'],
  ['Demi Lovato','Musician'],
  ['Nick Jonas','Musician'],
  ['Joe Jonas','Musician'],
  ['Kevin Jonas','Musician'],
  ['Pink','Musician'],
  ['Gwen Stefani','Musician'],
  ['Alanis Morissette','Musician'],
  ['Avril Lavigne','Musician'],
  ['Evanescence','Musician'],
  ['Hayley Williams','Musician'],
  ['Amy Winehouse','Musician'],
  ['Adele','Musician'],
  ['Joss Stone','Musician'],
  ['Sam Cooke','Musician'],
  ['Otis Redding','Musician'],
  ['James Brown','Musician'],
  ['Ray Charles','Musician'],
  ['B.B. King','Musician'],
  ['Muddy Waters','Musician'],
  ['Jimi Hendrix','Musician'],
  ['Jim Morrison','Musician'],
  ['Janis Joplin','Musician'],
  ['Kurt Cobain','Musician'],
  ['Chris Cornell','Musician'],
  ['Chester Bennington','Musician'],
  ['Layne Staley','Musician'],
  ['Scott Weiland','Musician'],
  ['Eddie Vedder','Musician'],
  ['Billy Corgan','Musician'],
  ['Dave Grohl','Musician'],
  ['Billy Joel','Musician'],
  ['Lionel Richie','Musician'],
  ['Tina Turner','Musician'],
  ['Diana Ross','Musician'],
  ['Gladys Knight','Musician'],
  ['Smokey Robinson','Musician'],
  ['Al Green','Musician'],
  ['Marvin Gaye','Musician'],
  ['Al Green','Musician'],
  ['Barry White','Musician'],
  ['Luther Vandross','Musician'],
  ['R. Kelly','Musician'],
  ['Boyz II Men','Musician'],
  ['TLC','Musician'],
  ['Destiny\'s Child','Musician'],
  ['En Vogue','Musician'],
  ['SWV','Musician'],
  ['Janet Jackson','Musician'],
  ['Paula Abdul','Musician'],
  ['Mariah Carey','Musician'],
  ['Celine Dion','Musician'],
  ['Shania Twain','Musician'],
  ['Faith Hill','Musician'],
  ['LeAnn Rimes','Musician'],
  ['Carrie Underwood','Musician'],
  ['Kelly Clarkson','Musician'],
  ['P!nk','Musician'],
  ['Missy Elliott','Musician'],
  ['Lil Kim','Musician'],
  ['Foxy Brown','Musician'],
  ['Da Brat','Musician'],
  ['Eve (rapper)','Musician'],
  ['Tweet (singer)','Musician'],
  ['Ashanti','Musician'],
  ['Ciara','Musician'],
  ['Keyshia Cole','Musician'],
  ['Ne-Yo','Musician'],
  ['Mario (singer)','Musician'],
  ['Omarion','Musician'],
  ['Bow Wow','Musician'],
  ['Soulja Boy','Musician'],
  ['Lil Romeo','Musician'],
  ['Chingy','Musician'],
  ['Juvenile (rapper)','Musician'],
  ['B.G. (rapper)','Musician'],
  ['Lil Boosie','Musician'],
  ['Kevin Gates','Musician'],
  ['Yo Gotti','Musician'],
  ['Gucci Mane','Musician'],
  ['Waka Flocka Flame','Musician'],
  ['2 Chainz','Musician'],
  ['Big K.R.I.T.','Musician'],
  ['T.I.','Musician'],
  ['Ludacris','Musician'],
  ['Lupe Fiasco','Musician'],
  ['Common (rapper)','Musician'],
  ['Mos Def','Musician'],
  ['Talib Kweli','Musician'],
  ['Dead Prez','Musician'],
  ['J. Cole','Musician'],
  ['Big Sean','Musician'],
  ['Meek Mill','Musician'],
  ['Rick Ross','Musician'],
  ['Wale (rapper)','Musician'],
  ['Wiz Khalifa','Musician'],
  ['Mac Miller','Musician'],
  ['Juice Wrld','Musician'],
  ['Xxxtentacion','Musician'],
  ['Lil Peep','Musician'],
  ['Trippie Redd','Musician'],
  ['Lil Uzi Vert','Musician'],
  ['Playboi Carti','Musician'],
  ['Travis Scott','Musician'],
  ['Jack Harlow','Musician'],
  ['Rod Wave','Musician'],
  ['Polo G','Musician'],
  ['NBA YoungBoy','Musician'],
  ['Tyler the Creator','Musician'],
  ['Frank Ocean','Musician'],
  ['Donald Glover','Musician'],
  ['Chance the Rapper','Musician'],
  ['Megan Thee Stallion','Musician'],
  ['Doja Cat','Musician'],
  ['Jhené Aiko','Musician'],
  ['Kehlani','Musician'],
  ['Normani','Musician'],
  ['Victoria Monét','Musician'],
  ['Sabrina Carpenter','Musician'],
  ['Conan Gray','Musician'],
  ['Noah Kahan','Musician'],
  ['Troye Sivan','Musician'],
  ['Omar Apollo','Musician'],
  ['Phoebe Bridgers','Musician'],
  ['Girl in Red','Musician'],
  ['Hozier','Musician'],
  ['Lewis Capaldi','Musician'],
  ['James Bay','Musician'],
  ['Sam Fender','Musician'],
  ['Dermot Kennedy','Musician'],
  ['Niall Horan','Musician'],
  ['Liam Payne','Musician'],
  ['Louis Tomlinson','Musician'],
  ['Zayn Malik','Musician'],
  ['Future (rapper)','Musician'],
  ['Lil Baby','Musician'],
  ['Gunna (rapper)','Musician'],
  ['21 Savage','Musician'],
  ['Meek Mill','Musician'],

  // Latin music
  ['Bad Bunny','Musician'],
  ['J Balvin','Musician'],
  ['Maluma','Musician'],
  ['Daddy Yankee','Musician'],
  ['Ozuna','Musician'],
  ['Anuel AA','Musician'],
  ['Rauw Alejandro','Musician'],
  ['Karol G','Musician'],
  ['Becky G','Musician'],
  ['Rosalía','Musician'],
  ['Marc Anthony','Musician'],
  ['Ricky Martin','Musician'],
  ['Enrique Iglesias','Musician'],
  ['Juanes','Musician'],
  ['Carlos Santana','Musician'],
  ['Gloria Estefan','Musician'],
  ['Celia Cruz','Musician'],
  ['Marc Anthony','Musician'],
  ['Luis Fonsi','Musician'],
  ['Nicky Jam','Musician'],
  ['Romeo Santos','Musician'],
  ['Prince Royce','Musician'],
  ['Aventura','Musician'],
  ['Farruko','Musician'],
  ['Sech','Musician'],
  ['Jhay Cortez','Musician'],

  // African musicians
  ['Wizkid','Musician'],
  ['Davido','Musician'],
  ['Burna Boy','Musician'],
  ['Tiwa Savage','Musician'],
  ['Yemi Alade','Musician'],
  ['Mr Eazi','Musician'],
  ['Fireboy DML','Musician'],
  ['Rema (singer)','Musician'],
  ['Ckay','Musician'],
  ['Tems','Musician'],
  ['Asake','Musician'],
  ['Omah Lay','Musician'],
  ['Ayra Starr','Musician'],
  ['Simi (singer)','Musician'],
  ['Adekunle Gold','Musician'],
  ['Falz','Musician'],
  ['Olamide','Musician'],
  ['Phyno','Musician'],
  ['2Baba','Musician'],
  ['Fela Kuti','Musician'],
  ['Youssou N\'Dour','Musician'],
  ['Angélique Kidjo','Musician'],
  ['Salif Keita','Musician'],
  ['Amadou et Mariam','Musician'],
  ['Baaba Maal','Musician'],
  ['Ali Farka Touré','Musician'],

  // British musicians
  ['Adele','Musician'],
  ['Ed Sheeran','Musician'],
  ['Harry Styles','Musician'],
  ['Dua Lipa','Musician'],
  ['Sam Smith','Musician'],
  ['Lewis Capaldi','Musician'],
  ['Niall Horan','Musician'],
  ['Liam Payne','Musician'],
  ['Louis Tomlinson','Musician'],
  ['Zayn Malik','Musician'],
  ['James Bay','Musician'],
  ['Sam Fender','Musician'],
  ['Dermot Kennedy','Musician'],
  ['Florence Welch','Musician'],
  ['Amy Winehouse','Musician'],
  ['Lily Allen','Musician'],
  ['Charli XCX','Musician'],
  ['Rita Ora','Musician'],
  ['Paloma Faith','Musician'],
  ['Jessie J','Musician'],
  ['Leona Lewis','Musician'],
  ['Emeli Sandé','Musician'],
  ['Ellie Goulding','Musician'],
  ['Ellie Goulding','Musician'],
  ['Jess Glynne','Musician'],
  ['Ella Henderson','Musician'],
  ['Anne-Marie','Musician'],
  ['Mabel (singer)','Musician'],
  ['Raye (singer)','Musician'],
  ['FKA Twigs','Musician'],
  ['M.I.A.','Musician'],
  ['Santigold','Musician'],
  ['M.I.A.','Musician'],
  ['Stormzy','Musician'],
  ['Dave (rapper)','Musician'],
  ['J Hus','Musician'],
  ['Headie One','Musician'],
  ['Central Cee','Musician'],
  ['Unknown T','Musician'],
  ['Aitch (rapper)','Musician'],
  ['Digga D','Musician'],
  ['Slowthai','Musician'],
  ['AJ Tracey','Musician'],
  ['Skepta','Musician'],
  ['Ghetts','Musician'],
  ['Giggs (rapper)','Musician'],
  ['Kano (rapper)','Musician'],
  ['Dizzee Rascal','Musician'],
  ['Wiley (rapper)','Musician'],
  ['Tinchy Stryder','Musician'],
  ['N-Dubz','Musician'],
  ['Craig David','Musician'],
  ['James Arthur','Musician'],
  ['Olly Murs','Musician'],
  ['One Direction','Musician'],

  // ══════════════════════════════════════════════════════
  // FOOTBALL / SOCCER PLAYERS — GLOBAL
  // ══════════════════════════════════════════════════════
  ['Lionel Messi','Athlete'],
  ['Cristiano Ronaldo','Athlete'],
  ['Kylian Mbappé','Athlete'],
  ['Erling Haaland','Athlete'],
  ['Neymar','Athlete'],
  ['Mohamed Salah','Athlete'],
  ['Sadio Mané','Athlete'],
  ['Robert Lewandowski','Athlete'],
  ['Luka Modrić','Athlete'],
  ['Karim Benzema','Athlete'],
  ['Vinicius Junior','Athlete'],
  ['Rodri','Athlete'],
  ['Kevin De Bruyne','Athlete'],
  ['Harry Kane','Athlete'],
  ['Raheem Sterling','Athlete'],
  ['Marcus Rashford','Athlete'],
  ['Bukayo Saka','Athlete'],
  ['Jude Bellingham','Athlete'],
  ['Phil Foden','Athlete'],
  ['Trent Alexander-Arnold','Athlete'],
  ['Virgil van Dijk','Athlete'],
  ['Bernardo Silva','Athlete'],
  ['Bruno Fernandes','Athlete'],
  ['David Beckham','Athlete'],
  ['Zinedine Zidane','Athlete'],
  ['Thierry Henry','Athlete'],
  ['Ronaldo (Brazilian footballer)','Athlete'],
  ['Ronaldinho','Athlete'],
  ['Gareth Bale','Athlete'],
  ['Wayne Rooney','Athlete'],
  ['Frank Lampard','Athlete'],
  ['Steven Gerrard','Athlete'],
  ['Rio Ferdinand','Athlete'],
  ['Didier Drogba','Athlete'],
  ['Samuel Eto\'o','Athlete'],
  ['Mesut Özil','Athlete'],
  ['Toni Kroos','Athlete'],
  ['Thomas Müller','Athlete'],
  ['Alessandro Del Piero','Athlete'],
  ['Francesco Totti','Athlete'],
  ['Andrea Pirlo','Athlete'],
  ['Gianluigi Buffon','Athlete'],
  ['Paolo Maldini','Athlete'],
  ['Fabio Cannavaro','Athlete'],
  ['Roberto Baggio','Athlete'],
  ['Andrés Iniesta','Athlete'],
  ['Xavi Hernández','Athlete'],
  ['Iker Casillas','Athlete'],
  ['Raúl González','Athlete'],
  ['Fernando Torres','Athlete'],
  ['David Villa','Athlete'],
  ['Xabi Alonso','Athlete'],
  ['Luis Suárez','Athlete'],
  ['Diego Forlán','Athlete'],
  ['Edinson Cavani','Athlete'],
  ['Diego Godín','Athlete'],
  ['Ivan Rakitić','Athlete'],
  ['Robin van Persie','Athlete'],
  ['Ruud van Nistelrooy','Athlete'],
  ['Patrick Kluivert','Athlete'],
  ['Edgar Davids','Athlete'],
  ['Clarence Seedorf','Athlete'],
  ['Michael Ballack','Athlete'],
  ['Oliver Kahn','Athlete'],
  ['Bastian Schweinsteiger','Athlete'],
  ['Miroslav Klose','Athlete'],
  ['Jürgen Klinsmann','Athlete'],
  ['Lothar Matthäus','Athlete'],
  ['Marcel Desailly','Athlete'],
  ['Lilian Thuram','Athlete'],
  ['Patrick Vieira','Athlete'],
  ['Robert Pires','Athlete'],
  ['Eric Cantona','Athlete'],
  ['Pierre-Emerick Aubameyang','Athlete'],
  ['Wilfried Zaha','Athlete'],
  ['Yaya Touré','Athlete'],
  ['Kolo Touré','Athlete'],
  ['Riyad Mahrez','Athlete'],
  ['Naby Keïta','Athlete'],
  ['Ousmane Dembélé','Athlete'],
  ['Raphaël Varane','Athlete'],
  ['Kingsley Coman','Athlete'],
  ['Olivier Giroud','Athlete'],
  ['Antoine Griezmann','Athlete'],
  ['Paul Pogba','Athlete'],
  ['N\'Golo Kanté','Athlete'],
  ['Presnel Kimpembe','Athlete'],
  ['Sofiane Feghouli','Athlete'],
  ['Youcef Atal','Athlete'],
  ['Achraf Hakimi','Athlete'],
  ['Hakim Ziyech','Athlete'],
  ['Yassine Bounou','Athlete'],
  ['Azzedine Ounahi','Athlete'],
  ['Sofyan Amrabat','Athlete'],
  ['Sadio Mané','Athlete'],
  ['Edouard Mendy','Athlete'],
  ['Kalidou Koulibaly','Athlete'],
  ['Idrissa Gueye','Athlete'],
  ['Ismaïla Sarr','Athlete'],
  ['Cheikhou Kouyaté','Athlete'],
  ['Wilfried Bony','Athlete'],
  ['Victor Osimhen','Athlete'],
  ['Kelechi Iheanacho','Athlete'],
  ['Alex Iwobi','Athlete'],
  ['Ola Aina','Athlete'],
  ['Taiwo Awoniyi','Athlete'],
  ['Emmanuel Amunike','Athlete'],
  ['Austin Jay-Jay Okocha','Athlete'],
  ['Nwankwo Kanu','Athlete'],
  ['Obafemi Martins','Athlete'],
  ['John Obi Mikel','Athlete'],
  ['Vincent Enyeama','Athlete'],
  ['Chukwuemeka Okonkwo','Athlete'],
  ['Gernot Rohr','Director'],
  ['Lionel Messi','Athlete'],
  ['Angel Di María','Athlete'],
  ['Paulo Dybala','Athlete'],
  ['Sergio Agüero','Athlete'],
  ['Gabriel Batistuta','Athlete'],
  ['Diego Maradona','Athlete'],
  ['Mario Kempes','Athlete'],
  ['Oscar (footballer)','Athlete'],
  ['Neymar','Athlete'],
  ['Pelé','Athlete'],
  ['Zico','Athlete'],
  ['Rivaldo','Athlete'],
  ['Ronaldinho','Athlete'],
  ['Ronaldo (Brazilian footballer)','Athlete'],
  ['Roberto Carlos','Athlete'],
  ['Cafu','Athlete'],
  ['Falcão','Athlete'],
  ['Romário','Athlete'],
  ['Bebeto','Athlete'],
  ['Sócrates','Athlete'],
  ['Garrincha','Athlete'],
  ['Rivelino','Athlete'],
  ['Gilmar','Athlete'],
  ['Son Heung-min','Athlete'],
  ['Park Ji-sung','Athlete'],
  ['Ahn Jung-hwan','Athlete'],
  ['Lee Dong-gook','Athlete'],
  ['Ki Sung-yueng','Athlete'],
  ['Heung-min Son','Athlete'],
  ['Shinji Kagawa','Athlete'],
  ['Shunsuke Nakamura','Athlete'],
  ['Keisuke Honda','Athlete'],
  ['Hidetoshi Nakata','Athlete'],
  ['Yasuhito Endo','Athlete'],
  ['Makoto Hasebe','Athlete'],

  // ══════════════════════════════════════════════════════
  // NFL PLAYERS
  // ══════════════════════════════════════════════════════
  ['Tom Brady','Athlete'],
  ['Patrick Mahomes','Athlete'],
  ['Josh Allen','Athlete'],
  ['Joe Burrow','Athlete'],
  ['Justin Herbert','Athlete'],
  ['Lamar Jackson','Athlete'],
  ['Dak Prescott','Athlete'],
  ['Aaron Rodgers','Athlete'],
  ['Russell Wilson','Athlete'],
  ['Jalen Hurts','Athlete'],
  ['Trevor Lawrence','Athlete'],
  ['Kyler Murray','Athlete'],
  ['Tua Tagovailoa','Athlete'],
  ['Davante Adams','Athlete'],
  ['Tyreek Hill','Athlete'],
  ['Stefon Diggs','Athlete'],
  ['Justin Jefferson','Athlete'],
  ['Cooper Kupp','Athlete'],
  ['Ja\'Marr Chase','Athlete'],
  ['Mike Evans','Athlete'],
  ['Deebo Samuel','Athlete'],
  ['Odell Beckham Jr.','Athlete'],
  ['Antonio Brown','Athlete'],
  ['Calvin Johnson','Athlete'],
  ['Randy Moss','Athlete'],
  ['Jerry Rice','Athlete'],
  ['Emmitt Smith','Athlete'],
  ['Walter Payton','Athlete'],
  ['Barry Sanders','Athlete'],
  ['Bo Jackson','Athlete'],
  ['Lawrence Taylor','Athlete'],
  ['Reggie White','Athlete'],
  ['Deion Sanders','Athlete'],
  ['Michael Irvin','Athlete'],
  ['Troy Aikman','Athlete'],
  ['Joe Montana','Athlete'],
  ['John Elway','Athlete'],
  ['Dan Marino','Athlete'],
  ['Peyton Manning','Athlete'],
  ['Brett Favre','Athlete'],
  ['Joe Namath','Athlete'],
  ['Terry Bradshaw','Athlete'],
  ['Mean Joe Greene','Athlete'],
  ['Dick Butkus','Athlete'],

  // ══════════════════════════════════════════════════════
  // NBA PLAYERS
  // ══════════════════════════════════════════════════════
  ['LeBron James','Athlete'],
  ['Michael Jordan','Athlete'],
  ['Stephen Curry','Athlete'],
  ['Kevin Durant','Athlete'],
  ['Giannis Antetokounmpo','Athlete'],
  ['Nikola Jokić','Athlete'],
  ['Joel Embiid','Athlete'],
  ['Luka Dončić','Athlete'],
  ['Trae Young','Athlete'],
  ['Damian Lillard','Athlete'],
  ['Donovan Mitchell','Athlete'],
  ['Jayson Tatum','Athlete'],
  ['Anthony Davis','Athlete'],
  ['Russell Westbrook','Athlete'],
  ['James Harden','Athlete'],
  ['Kyrie Irving','Athlete'],
  ['Chris Paul','Athlete'],
  ['DeMar DeRozan','Athlete'],
  ['Devin Booker','Athlete'],
  ['Ja Morant','Athlete'],
  ['Zion Williamson','Athlete'],
  ['Karl-Anthony Towns','Athlete'],
  ['Bam Adebayo','Athlete'],
  ['Draymond Green','Athlete'],
  ['Klay Thompson','Athlete'],
  ['Shaquille O\'Neal','Athlete'],
  ['Charles Barkley','Athlete'],
  ['Patrick Ewing','Athlete'],
  ['Hakeem Olajuwon','Athlete'],
  ['David Robinson','Athlete'],
  ['Scottie Pippen','Athlete'],
  ['Dennis Rodman','Athlete'],
  ['Allen Iverson','Athlete'],
  ['Dirk Nowitzki','Athlete'],
  ['Steve Nash','Athlete'],
  ['Jason Kidd','Athlete'],
  ['Gary Payton','Athlete'],
  ['Karl Malone','Athlete'],
  ['John Stockton','Athlete'],
  ['Isiah Thomas','Athlete'],
  ['Larry Bird','Athlete'],
  ['Magic Johnson','Athlete'],
  ['Bill Russell','Athlete'],
  ['Kareem Abdul-Jabbar','Athlete'],
  ['Julius Erving','Athlete'],
  ['Moses Malone','Athlete'],
  ['Wilt Chamberlain','Athlete'],
  ['Oscar Robertson','Athlete'],
  ['Bob Cousy','Athlete'],
  ['Pete Maravich','Athlete'],

  // ══════════════════════════════════════════════════════
  // OTHER GLOBAL ATHLETES — Tennis, Golf, Boxing, MMA
  // ══════════════════════════════════════════════════════
  ['Serena Williams','Athlete'],
  ['Venus Williams','Athlete'],
  ['Roger Federer','Athlete'],
  ['Rafael Nadal','Athlete'],
  ['Novak Djokovic','Athlete'],
  ['Andy Murray','Athlete'],
  ['Carlos Alcaraz','Athlete'],
  ['Jannik Sinner','Athlete'],
  ['Daniil Medvedev','Athlete'],
  ['Alexander Zverev','Athlete'],
  ['Stefanos Tsitsipas','Athlete'],
  ['Andrey Rublev','Athlete'],
  ['Emma Raducanu','Athlete'],
  ['Iga Świątek','Athlete'],
  ['Ashleigh Barty','Athlete'],
  ['Naomi Osaka','Athlete'],
  ['Simona Halep','Athlete'],
  ['Angelique Kerber','Athlete'],
  ['Maria Sharapova','Athlete'],
  ['Caroline Wozniacki','Athlete'],
  ['Martina Navratilova','Athlete'],
  ['Steffi Graf','Athlete'],
  ['Monica Seles','Athlete'],
  ['Billie Jean King','Athlete'],
  ['Chris Evert','Athlete'],
  ['Tiger Woods','Athlete'],
  ['Rory McIlroy','Athlete'],
  ['Phil Mickelson','Athlete'],
  ['Dustin Johnson','Athlete'],
  ['Brooks Koepka','Athlete'],
  ['Bryson DeChambeau','Athlete'],
  ['Justin Thomas','Athlete'],
  ['Jordan Spieth','Athlete'],
  ['Muhammad Ali','Athlete'],
  ['Mike Tyson','Athlete'],
  ['Floyd Mayweather Jr.','Athlete'],
  ['Manny Pacquiao','Athlete'],
  ['Canelo Álvarez','Athlete'],
  ['Deontay Wilder','Athlete'],
  ['Anthony Joshua','Athlete'],
  ['Tyson Fury','Athlete'],
  ['Ryan Garcia','Athlete'],
  ['Gervonta Davis','Athlete'],
  ['Conor McGregor','Athlete'],
  ['Khabib Nurmagomedov','Athlete'],
  ['Jon Jones','Athlete'],
  ['Israel Adesanya','Athlete'],
  ['Francis Ngannou','Athlete'],
  ['Ronda Rousey','Athlete'],
  ['Amanda Nunes','Athlete'],
  ['Valentina Shevchenko','Athlete'],
  ['Rose Namajunas','Athlete'],
  ['Simone Biles','Athlete'],
  ['Nadia Comaneci','Athlete'],
  ['Usain Bolt','Athlete'],
  ['Carl Lewis','Athlete'],
  ['Jesse Owens','Athlete'],
  ['Florence Griffith Joyner','Athlete'],
  ['Allyson Felix','Athlete'],
  ['Eliud Kipchoge','Athlete'],
  ['Lewis Hamilton','Athlete'],
  ['Michael Schumacher','Athlete'],
  ['Ayrton Senna','Athlete'],
  ['Max Verstappen','Athlete'],
  ['Charles Leclerc','Athlete'],
  ['Michael Phelps','Athlete'],
  ['Mark Spitz','Athlete'],
  ['Katie Ledecky','Athlete'],
  ['Ryan Lochte','Athlete'],
  ['Caeleb Dressel','Athlete'],
  ['Wayne Gretzky','Athlete'],
  ['Mario Lemieux','Athlete'],
  ['Sidney Crosby','Athlete'],
  ['Alex Ovechkin','Athlete'],
  ['Connor McDavid','Athlete'],
  ['Gordie Howe','Athlete'],
  ['Bobby Orr','Athlete'],
  ['Patrick Roy','Athlete'],
  ['Martin Brodeur','Athlete'],
  ['Sachin Tendulkar','Athlete'],
  ['Brian Lara','Athlete'],
  ['Vivian Richards','Athlete'],
  ['Wasim Akram','Athlete'],
  ['Shane Warne','Athlete'],
  ['Steve Waugh','Athlete'],
  ['Ricky Ponting','Athlete'],
  ['Virat Kohli','Athlete'],
  ['MS Dhoni','Athlete'],
  ['Rohit Sharma','Athlete'],

  // ══════════════════════════════════════════════════════
  // DIRECTORS & PRODUCERS
  // ══════════════════════════════════════════════════════
  ['Steven Spielberg','Director'],
  ['Christopher Nolan','Director'],
  ['Martin Scorsese','Director'],
  ['Quentin Tarantino','Director'],
  ['James Cameron','Director'],
  ['Ridley Scott','Director'],
  ['David Fincher','Director'],
  ['Denis Villeneuve','Director'],
  ['Wes Anderson','Director'],
  ['Sofia Coppola','Director'],
  ['Ava DuVernay','Director'],
  ['Greta Gerwig','Director'],
  ['Jordan Peele','Director'],
  ['Ryan Coogler','Director'],
  ['Alfonso Cuarón','Director'],
  ['Guillermo del Toro','Director'],
  ['Pedro Almodóvar','Director'],
  ['Bong Joon-ho','Director'],
  ['Tim Burton','Director'],
  ['J. J. Abrams','Director'],
  ['Peter Jackson','Director'],
  ['Ron Howard','Director'],
  ['Clint Eastwood','Director'],
  ['Darren Aronofsky','Director'],
  ['Spike Lee','Director'],
  ['Francis Ford Coppola','Director'],
  ['Stanley Kubrick','Director'],
  ['Billy Wilder','Director'],
  ['Alfred Hitchcock','Director'],
  ['Orson Welles','Director'],
  ['Akira Kurosawa','Director'],
  ['Ingmar Bergman','Director'],
  ['Federico Fellini','Director'],
  ['Jean-Luc Godard','Director'],
  ['François Truffaut','Director'],
  ['Roman Polanski','Director'],
  ['Brian De Palma','Director'],
  ['Oliver Stone','Director'],
  ['Michael Mann','Director'],
  ['Paul Thomas Anderson','Director'],
  ['Terrence Malick','Director'],
  ['Coen Brothers','Director'],
  ['Joel Coen','Director'],
  ['Ethan Coen','Director'],
  ['Woody Allen','Director'],
  ['Mike Leigh','Director'],
  ['Ken Loach','Director'],
  ['Mike Figgis','Director'],
  ['Danny Boyle','Director'],
  ['Sam Mendes','Director'],
  ['Christopher Guest','Director'],
  ['Gareth Edwards','Director'],
  ['Patty Jenkins','Director'],
  ['Chloé Zhao','Director'],
  ['Lana Wachowski','Director'],
  ['Lilly Wachowski','Director'],
  ['Kathryn Bigelow','Director'],
  ['Nancy Meyers','Director'],
  ['Nora Ephron','Director'],
  ['Penny Marshall','Director'],
  ['Barbra Streisand','Director'],
  ['Jerry Bruckheimer','Movie Producer'],
  ['Kathleen Kennedy','Movie Producer'],
  ['Kevin Feige','Movie Producer'],
  ['Jason Blum','Movie Producer'],
  ['Judd Apatow','Movie Producer'],
  ['Ryan Murphy','Movie Producer'],
  ['Shonda Rhimes','Movie Producer'],
  ['Tyler Perry','Movie Producer'],
  ['Lorne Michaels','Movie Producer'],
  ['John Hughes','Movie Producer'],
  ['Robert Evans','Movie Producer'],
  ['Scott Rudin','Movie Producer'],
  ['Brian Grazer','Movie Producer'],
  ['Imagine Entertainment','Movie Producer'],

  // ══════════════════════════════════════════════════════
  // COMEDIANS
  // ══════════════════════════════════════════════════════
  ['Dave Chappelle','Comedian'],
  ['Chris Rock','Comedian'],
  ['Kevin Hart','Comedian'],
  ['Jerry Seinfeld','Comedian'],
  ['Eddie Murphy','Comedian'],
  ['Jim Carrey','Comedian'],
  ['Robin Williams','Comedian'],
  ['Ellen DeGeneres','Comedian'],
  ['Tina Fey','Comedian'],
  ['Amy Poehler','Comedian'],
  ['John Mulaney','Comedian'],
  ['Hasan Minhaj','Comedian'],
  ['Hannah Gadsby','Comedian'],
  ['Ali Wong','Comedian'],
  ['Trevor Noah','Comedian'],
  ['Conan O\'Brien','Comedian'],
  ['Jimmy Fallon','Comedian'],
  ['Jimmy Kimmel','Comedian'],
  ['Stephen Colbert','Comedian'],
  ['Bill Hader','Comedian'],
  ['Andy Samberg','Comedian'],
  ['Pete Davidson','Comedian'],
  ['Wanda Sykes','Comedian'],
  ['Nikki Glaser','Comedian'],
  ['Bill Burr','Comedian'],
  ['Louis C.K.','Comedian'],
  ['Sarah Silverman','Comedian'],
  ['Aziz Ansari','Comedian'],
  ['Russell Brand','Comedian'],
  ['Ricky Gervais','Comedian'],
  ['James Corden','Comedian'],
  ['Graham Norton','Comedian'],
  ['Russell Howard','Comedian'],
  ['Michael McIntyre','Comedian'],
  ['Lee Mack','Comedian'],
  ['David Mitchell','Comedian'],
  ['Romesh Ranganathan','Comedian'],
  ['Nish Kumar','Comedian'],
  ['Micky Flanagan','Comedian'],
  ['Dara O\'Briain','Comedian'],
  ['Dylan Moran','Comedian'],
  ['Tommy Tiernan','Comedian'],
  ['Des Bishop','Comedian'],
  ['Stewart Lee','Comedian'],
  ['Rich Hall','Comedian'],
  ['Omid Djalili','Comedian'],
  ['Jimmy Carr','Comedian'],
  ['Lee Evans','Comedian'],
  ['Frank Skinner','Comedian'],
  ['Jack Dee','Comedian'],

  // ══════════════════════════════════════════════════════
  // MODELS — Global
  // ══════════════════════════════════════════════════════
  ['Gigi Hadid','Model'],
  ['Bella Hadid','Model'],
  ['Kendall Jenner','Model'],
  ['Cara Delevingne','Model'],
  ['Adriana Lima','Model'],
  ['Heidi Klum','Model'],
  ['Naomi Campbell','Model'],
  ['Kate Moss','Model'],
  ['Cindy Crawford','Model'],
  ['Tyra Banks','Model'],
  ['Karlie Kloss','Model'],
  ['Ashley Graham','Model'],
  ['Irina Shayk','Model'],
  ['Candice Swanepoel','Model'],
  ['Bar Refaeli','Model'],
  ['Miranda Kerr','Model'],
  ['Emily Ratajkowski','Model'],
  ['Chrissy Teigen','Model'],
  ['Winnie Harlow','Model'],
  ['Adwoa Aboah','Model'],
  ['Jourdan Dunn','Model'],
  ['Jasmine Tookes','Model'],
  ['Joan Smalls','Model'],
  ['Liya Kebede','Model'],
  ['Alek Wek','Model'],
  ['Alex Wek','Model'],
  ['Natalia Vodianova','Model'],
  ['Karolína Kurková','Model'],
  ['Magdalena Frąckowiak','Model'],
  ['Anja Rubik','Model'],
  ['Doutzen Kroes','Model'],
  ['Lara Stone','Model'],
  ['Marloes Horst','Model'],
  ['Famke Janssen','Model'],
  ['Kim Noorda','Model'],
  ['Hana Jiříčková','Model'],
  ['Petra Nemcova','Model'],
  ['Eva Herzigova','Model'],
  ['Adriana Sklenaříková','Model'],
  ['Liis Windischmann','Model'],
  ['Valentina Zelyaeva','Model'],
  ['Sasha Pivovarova','Model'],
  ['Natasha Poly','Model'],
  ['Vlada Roslyakova','Model'],
  ['Slata Maltseva','Model'],
  ['Lily Aldridge','Model'],
  ['Behati Prinsloo','Model'],
  ['Alessandra Ambrosio','Model'],
  ['Ana Beatriz Barros','Model'],
  ['Izabel Goulart','Model'],
  ['Mariana Weickert','Model'],
  ['Fernanda Tavares','Model'],
  ['Raica Oliveira','Model'],
  ['Jeisa Chiminazzo','Model'],
  ['Aline Nakashima','Model'],
  ['Gisele Bündchen','Model'],

  // ══════════════════════════════════════════════════════
  // DIGITAL CREATORS / INFLUENCERS
  // ══════════════════════════════════════════════════════
  ['MrBeast','Creator'],
  ['PewDiePie','Creator'],
  ['Ninja','Creator'],
  ['Logan Paul','Creator'],
  ['Jake Paul','Creator'],
  ['Emma Chamberlain','Creator'],
  ['Lilly Singh','Creator'],
  ['Markiplier','Creator'],
  ['Jacksepticeye','Creator'],
  ['James Charles','Creator'],
  ['David Dobrik','Creator'],
  ['Jeffree Star','Creator'],
  ['Shane Dawson','Creator'],
  ['Zoella','Creator'],
  ['Alfie Deyes','Creator'],
  ['Casey Neistat','Creator'],
  ['Yes Theory','Creator'],
  ['Nas Daily','Creator'],
  ['MKBHD','Creator'],
  ['Linus Sebastian','Creator'],
  ['Marques Brownlee','Creator'],
  ['Mark Dice','Creator'],
  ['Philip DeFranco','Creator'],
  ['Drama Alert','Creator'],
  ['Keemstar','Creator'],
  ['Pokimane','Creator'],
  ['Valkyrae','Creator'],
  ['Sykkuno','Creator'],
  ['Ludwig Ahgren','Creator'],
  ['Mizkif','Creator'],
  ['HasanAbi','Creator'],
  ['xQc','Creator'],
  ['Amouranth','Creator'],
  ['Kai Cenat','Creator'],
  ['IShowSpeed','Creator'],
  ['Adin Ross','Creator'],
  ['Bronny James','Creator'],
  ['Overtime Megan','Creator'],
  ['Deestroying','Creator'],
  ['Dude Perfect','Creator'],
  ['How Ridiculous','Creator'],
  ['Corridor Crew','Creator'],
  ['Kurzgesagt','Creator'],
  ['Veritasium','Creator'],
  ['Vsauce','Creator'],
  ['CGP Grey','Creator'],
  ['TED-Ed','Creator'],
  ['Numberphile','Creator'],

];

// ─── Helpers ───────────────────────────────────────────────────────────────
function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

function delay(ms) {
  return new Promise(r => setTimeout(r, ms));
}

// ─── Fetch Wikipedia category members ─────────────────────────────────────
export async function fetchCategoryMembers(category, cap = 300) {
  const collected = [];
  let continueToken = null;

  while (collected.length < cap) {
    const params = new URLSearchParams({
      action:      'query',
      list:        'categorymembers',
      cmtitle:     `Category:${category}`,
      cmlimit:     500,
      cmtype:      'page',
      cmnamespace: 0,
      format:      'json',
      origin:      '*',
    });
    if (continueToken) params.set('cmcontinue', continueToken);

    let data;
    try {
      const res = await fetch(`${WIKI_API}?${params}`);
      data = await res.json();
    } catch { break; }

    const members = data.query?.categorymembers || [];
    collected.push(...members.map(m => m.title));

    if (data.continue?.cmcontinue && collected.length < cap) {
      continueToken = data.continue.cmcontinue;
      await delay(120);
    } else {
      break;
    }
  }

  return collected.slice(0, cap);
}

// ─── Batch-fetch page details (photo + extract) for up to 50 titles ────────
export async function fetchPageDetails(titles) {
  if (!titles.length) return [];

  const params = new URLSearchParams({
    action:      'query',
    format:      'json',
    prop:        'pageimages|extracts',
    exintro:     true,
    exsentences: 2,
    explaintext: true,
    titles:      titles.join('|'),
    pithumbsize: 500,
    origin:      '*',
    redirects:   1,
  });

  let data;
  try {
    const res = await fetch(`${WIKI_API}?${params}`);
    data = await res.json();
  } catch { return []; }

  return Object.values(data.query?.pages || {})
    .filter(p => p.thumbnail?.source && !p.missing && p.pageid > 0)
    .map(p => ({
      id:      p.pageid,
      name:    p.title,
      image:   p.thumbnail.source,
      bio:     (p.extract || '').replace(/\n.*/s, '').trim(),
      wikiUrl: `https://en.wikipedia.org/wiki/${encodeURIComponent(p.title.replace(/ /g, '_'))}`,
    }));
}

// ─── Open Library: fetch notable authors as "Creators" ────────────────────
export async function fetchOpenLibraryAuthors(queries) {
  const results = [];
  for (const q of queries) {
    try {
      const res  = await fetch(`${OL_API}/search/authors.json?q=${encodeURIComponent(q)}&limit=10`);
      const data = await res.json();
      for (const author of (data.docs || []).slice(0, 5)) {
        if (author.key && author.name) {
          const coverId  = author.photos?.[0];
          const photoUrl = coverId
            ? `https://covers.openlibrary.org/a/id/${coverId}-L.jpg`
            : null;
          if (photoUrl) {
            results.push({
              id:       'ol_' + author.key.replace('/authors/', ''),
              name:     author.name,
              image:    photoUrl,
              bio:      author.bio || `${author.name} — celebrated author and creator.`,
              category: 'Creator',
            });
          }
        }
      }
      await delay(100);
    } catch { /* skip */ }
  }
  return results;
}

// ─── Build full celebrity object ──────────────────────────────────────────
let _idCounter = 10000;
export function buildCelebrity(raw, category) {
  return {
    id:          raw.id || ++_idCounter,
    name:        raw.name,
    category,
    image:       raw.image,
    cover:       buildCoverUrl(raw.id || _idCounter, category),
    bio:         raw.bio || `${raw.name} is a world-renowned ${category.toLowerCase()}.`,
    wikiUrl:     raw.wikiUrl || '',
    verified:    isLikelyFamous(raw.name),
    followers:   randomFollowers(),
    posts:       Math.floor(Math.random() * 900) + 50,
    trending:    Math.random() > 0.78,
    newlyJoined: Math.random() > 0.88,
  };
}

function buildCoverUrl(id) {
  const seed = typeof id === 'number' ? id : Math.abs(hashStr(String(id)));
  return `https://picsum.photos/seed/${seed % 1000}/1200/400`;
}

function randomFollowers() {
  const ranges  = [[0.1,0.9],[1,4.9],[5,9.9],[10,49],[50,100]];
  const weights = [30, 35, 20, 10, 5];
  const total   = weights.reduce((a, b) => a + b, 0);
  let rand = Math.random() * total;
  for (let i = 0; i < weights.length; i++) {
    rand -= weights[i];
    if (rand <= 0) {
      const [lo, hi] = ranges[i];
      const val = lo + Math.random() * (hi - lo);
      return val >= 10 ? `${val.toFixed(0)}M` : `${val.toFixed(1)}M`;
    }
  }
  return '1M';
}

function isLikelyFamous(name) {
  return name.split(' ').length <= 4 && !/\(/.test(name);
}

function hashStr(s) {
  let h = 0;
  for (const c of s) h = (Math.imul(31, h) + c.charCodeAt(0)) | 0;
  return h;
}
